### ISSUE TITLE
Hey there

### ISSUE THREAD

**Issue by Codynw42** [BambooSoftwareLLC/organization#1]
I happened to stumble across your page when i was looking around at companies in Ohio. Im actually from Ohio myself, near Akron.  ive lived here since i was born.  Im always looking to learn and meet new people in the dev world. If you ever need an extra body with a computer - i'm willing to help with what I can. Also I love the name of the LLC. It caught my eye because im a tech nerd obviously but i also love nature. It makes for a good sounding name, i like it.

**Comment by Burwin** [comment]
I'll send you an email
